### ISSUE TITLE
[Retail Bug Report] Pin button border texture is still visible (unlike the tracking button next to it)

### ISSUE THREAD

**Issue by Daenarys** [tukui-org/ElvUI#1052]
### What is the issue you are having?

The tracking button on the worldmap is missing the minimap border texture

### What is the expected behavior?

the minimap border texture should show around it

### What actually happened?

missing texture

### Suggested Solution/Workaround

![bug](https://github.com/tukui-org/ElvUI/assets/4172453/6f85b515-9c40-48b2-919f-0abaf389cc14)

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md).
- [X] I have verified ElvUI is up to date by checking /estatus.
- [X] I have verified my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verified my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
its actually the other way around, we removed the texture from the tracking and didnt for the ping which i will have to look into
