### ISSUE TITLE
Incorrect tracking for Dragonflight Fragments season maximum on datatext mouseover

### ISSUE THREAD

**Issue by Muspelful** [tukui-org/ElvUI#1117]
### Troubleshooting Steps

![WoWScrnShot_112223_171555](https://github.com/tukui-org/ElvUI/assets/4552499/508c404b-eeb5-43b6-83af-ec1abd797a35)
![WoWScrnShot_112223_171639](https://github.com/tukui-org/ElvUI/assets/4552499/06f531f7-f21e-4b5a-9d8a-238d559ead0e)
Note how the first screenshot shows the seasonal maximum for wyrm's crests is 30/180 on the datatext, but the actual maximum is at 90/180 in the second screenshot.

### Describe the expected behavior and what actually happened?

The datatext mouseover for crests should show the current progress towards the seasonal cap, a slash, then the current seasonal cap (e.g. if I have earned a total of 120 crests out of a possible 180, it should show 120/180).

Instead, the number before the slash is your current amount of crests, which is not the same, because you could, for instance, spend crests and have fewer than you've earned across the season.

### Reproducing the issue.

Earn any amount of season 3 crests. Spend some amount of them. Mouse over the Dragonflight Crests datatext and it will display the wrong amount.

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.
