### ISSUE TITLE
Minimap Tracking Icon being observed when hidden in Elvui settings

### ISSUE THREAD

**Issue by robbentenmann** [tukui-org/ElvUI#1183]
### Troubleshooting Steps

Steps:

In the Elvui Options, go to Map section.
Hide the minimap tracker

Status Pic:
![Pic3](https://github.com/tukui-org/ElvUI/assets/57543676/bc1b0432-cb4f-4377-83c1-4199ffc5325c)

UI Pic (see circled area):
![Pic1](https://github.com/tukui-org/ElvUI/assets/57543676/f6d9f745-af16-473f-ba4b-78edd2a8f4ea)

Options Pic:
![Pic2](https://github.com/tukui-org/ElvUI/assets/57543676/23b60183-b924-4079-9790-217808e76987)

### Describe the expected behavior and what actually happened?

Expected:
The tracker icon should be hidden.

Actual:
The tracker icon is showing up by the action bar.

### Reproducing the issue.

Steps:
- Log onto retail wow.
- Type /elvui.
- In the Elvui Options, go to Map section.
- Hide the minimap tracker

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by robbentenmann** [comment]
This is also happening in Wrath Classic as well.

![image](https://github.com/tukui-org/ElvUI/assets/57543676/9f80b3a6-52a3-4248-93a7-dcdaa66e5998)

**Comment by 1Botanica1** [comment]
When troubleshooting, please always go through all the steps.  You have other addons enabled there. 

This isssue is fixed in the dev version and will be in next release.

**Comment by robbentenmann** [comment]
Do we have an expected date for the next release @1Botanica1? Happy this will be fixed!

**Comment by Repooc** [comment]
No we do not give etas. We will release when we are don't exploring other stuff that is reported.

**Comment by kodewdle** [comment]
optionally, you can install the version early with the fix: [dev.zip](https://github.com/tukui-org/ElvUI/archive/refs/heads/development.zip) - still no ETA when this goes live

**Comment by Merathilis** [comment]
Fixed in 13.61
