### ISSUE TITLE
Errors from auto tracking reputation

### ISSUE THREAD

**Issue by dbgEpsilon** [tukui-org/ElvUI#1258]
### Troubleshooting Steps

![Screenshot 2024-07-25 121133](https://github.com/user-attachments/assets/f49fa05b-5e2a-4a7f-9041-99e40c849c6f)

### Describe the expected behavior and what actually happened?

Expected Behavior: Auto-tracking reputation based on recent rep gains.

Actual Behavior: Lua Errors and rep tracking unchanged.

Note: Errors stop with `Auto Track Reputation` disabled.

### Reproducing the issue.

I am not sure if all rep gains cause the issue, but I specifically noticed in dungeons where killing large numbers of mobs that yield rep was causing a ton of lag from the errors. In this specific case:

1. Enable `Auto Track Reputation`
2. Equip a tabard that gives/converts dungeon rep (I was using the Darkspear Tabard)
3. Enter a dungeons whose mobs give rep when killed (I was in Magister's Terrace)
4. Kill any mob that gives rep

### Lua Errors

```shell
Message: Interface/AddOns/ElvUI/Core/Modules/Misc/Misc.lua:151: attempt to call upvalue 'ExpandAllFactionHeaders' (a nil value)
Time: Thu Jul 25 12:08:53 2024
Count: 3
Stack: Interface/AddOns/ElvUI/Core/Modules/Misc/Misc.lua:151: attempt to call upvalue 'ExpandAllFactionHeaders' (a nil value)
[string "@Interface/AddOns/ElvUI/Core/Modules/Misc/Misc.lua"]:151: in function `?'
[string "@Interface/AddOns/ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:109: in function <...ies/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...ies/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...UI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals: self = <table> {
 QueueStatus = ElvUIQueueStatus {
 }
 modules = <table> {
 }
 BubbleFrame = Frame {
 }
 RaidMarkFrame = Frame {
 }
 Initialized = true
 baseName = "ElvUI"
 defaultModuleState = true
 hooks = <table> {
 }
 enabledState = true
 defaultModuleLibraries = <table> {
 }
 name = "ElvUI_Misc"
 orderedModules = <table> {
 }
 QuestRewardGoldIconFrame = ElvUI_QuestRewardGoldIconFrame {
 }
 QueueStatusDisplay = ElvUIQueueStatusDisplay {
 }
 RollBars = <table> {
 }
 moduleName = "Misc"
}
_ = "COMBAT_TEXT_UPDATE"
messagetype = "FACTION"
faction = "Darkspear Trolls"
rep = 300
data = <table> {
 hasBonusRepGain = false
 description = ""
 isHeaderWithRep = false
 isHeader = false
 currentReactionThreshold = 21000
 canSetInactive = false
 atWarWith = false
 isWatched = false
 isCollapsed = false
 canToggleAtWar = false
 nextReactionThreshold = 42000
 factionID = 1119
 name = "The Sons of Hodir"
 currentStanding = 25827
 isAccountWide = false
 isChild = false
 reaction = 7
}
(*temporary) = nil
(*temporary) = "attempt to call upvalue 'ExpandAllFactionHeaders' (a nil value)"
E = <table> {
 mylevel = 70
 Bags = <table> {
 }
 privateVars = <table> {
 }
 modules = <table> {
 }
 myspecRole = "DAMAGER"
 PriestColors = <table> {
 }
 db = <table> {
 }
 Layout = <table> {
 }
 Distributor = <table> {
 }
 MountText = <table> {
 }
 INCOMPATIBLE_ADDONS = <table> {
 }
 TimeIndicatorColors = <table> {
 }
 WorldMap = <table> {
 }
 TimeColors = <table> {
 }
 ShortValueDec = "%.1f"
 oUF = <table> {
 }
 Classic = false
 myrole = "DAMAGER"
 UFParent = ElvUFParent {
 }
 wowtoc = 110000
 InfoColor2 = ""
 myname = "Façade"
 ActionBars = <table> {
 }
 screenHeight = 1199.999878
 twoPixelsPlease = false
 ConfigModeLayouts = <table> {
 }
 DataTexts = <table> {
 }
 ClassName = <table> {
 }
 CreatureTypes = <table> {
 }
 Auras = <table> {
 }
 private = <table> {
 }
 ReverseTimer = <table> {
 }
 TagFunctions = <table> {
 }
 myClassID = 3
 UnlocalizedClasses = <table> {
 }
 MinimapSize = 220
 snapBars = <table> {
 }
 hooks = <table> {
 }
 SpecName = <table> {
 }
 GemTypeInfo = <table> {
 }
 StyleFilterDefaults = <table> {
 }
 physicalWidth = 3440
 versionString = "13.71"
 LSM = <table> {
 }
 InfoColor = ""
 CreatedMovers = <table> {
 }
 myLocalizedFaction = "Horde"
 myrace = "HighmountainTauren"
 StaticPopup_DisplayedFrames = <table> {
 }
 VehicleLocks = <table> {
 }
 myLocalizedRace = "Highmountain Tauren"
 myclass = "HUNTER"
 wowdate = "Jul 24 2024"
 PopupDialogs = <table> {
 }
 Chat = <table> {
 }
 myrealm = "Gilneas"
 LayoutMoverPositions = <table> {
 }
 global = <table> {
 }
 orderedModules = <table> {
 }
 Misc = <table> {
 }
 UnitFrames = <table> {
 }
 uiscale = 0.640000
 TBC = false
 AnimElastic = <table> {
 }
 media = <table> {
 }
 data = <table> {
 }
 Options = <table> {
 }
 toc = 110000
 HiddenFrame = Frame {
 }
 Media = <table> {
 }
 name = "ElvUI"
 TimeFormats = <table> {
 }
 ShortPrefixStyles = <table> {
 }
 versionDev = false
 Blizzard =
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by kodewdle** [comment]
fixed in dev
