### ISSUE TITLE
Unable to use quest item in the quest tracker

### ISSUE THREAD

**Issue by Stultusaur** [tukui-org/ElvUI#1280]
### Troubleshooting Steps

![error2](https://github.com/user-attachments/assets/71115f09-f216-4743-bdf5-8d395b4bfbbd)
![error3](https://github.com/user-attachments/assets/dc96dd5a-5bd3-4e3c-81d6-9486c8f4706e)

### Describe the expected behavior and what actually happened?

I expect it to use the quest item from the quest tracker. 

It does not always happen.
This was happening with and without addons running.
It does not generate an LUA error that I can post.

### Reproducing the issue.

Was able to reproduce after accepting a quest with the quest item, and going AFK for a few minutes, 

### Lua Errors

```shell
Cannot post the LUA error without enabling BugGrabber and BugSack
Because it is an  ADDON_PROTECTED_FUNCTION error, it does show the error.

I will edit this with the LUA error once I disable elvui debug mode.

EDIT:

3x [ADDON_ACTION_FORBIDDEN] AddOn 'ElvUI' tried to call the protected function 'UseQuestLogSpecialItem()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `UseQuestLogSpecialItem'
[string "@Blizzard_ObjectiveTracker/Blizzard_ObjectiveTrackerShared.lua"]:94: in function <...ObjectiveTracker/Blizzard_ObjectiveTrackerShared.lua:87>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
}

```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by gmanavarro** [comment]
+1

**Comment by tehSmoogs** [comment]
+1

**Comment by Avarios** [comment]
+1

**Comment by Flannair** [comment]
+1

**Comment by SleepTooLong** [comment]
Having the same issue, it works after I reload for a while, but then it suddenly stops working at some point

**Comment by hellojusi** [comment]
Same issue here. BugGrabber returns this error:

` [ADDON_ACTION_FORBIDDEN] AddOn 'ElvUI_SLE' tried to call the protected function 'UseQuestLogSpecialItem()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `UseQuestLogSpecialItem'
[string "@Blizzard_ObjectiveTracker/Blizzard_ObjectiveTrackerShared.lua"]:94: in function <...ObjectiveTracker/Blizzard_ObjectiveTrackerShared.lua:87>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
}`

**Comment by Rulob** [comment]
Same issue since 11.0 patch.

**Comment by Aeosora** [comment]
Same issue as well since 11.0. Can't seem to get it to go away either. I use Shadow and Light as well, but even after disabling Shadow and Light it doesn't go away.

**Comment by Prejudice182** [comment]
With `/edebug on`, I can now use the quest item, so its possible the taint is coming from somewhere else.

**Comment by Stultusaur** [comment]
> With `/edebug on`, I can now use the quest item, so its possible the taint is coming from somewhere else. ![image](https://private-user-images.githubusercontent.com/1422835/359071451-d034a873-5c2a-4898-822a-5c97d00588b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyODU5OTcsIm5iZiI6MTcyNDI4NTY5NywicGF0aCI6Ii8xNDIyODM1LzM1OTA3MTQ1MS1kMDM0YTg3My01YzJhLTQ4OTgtODIyYS01Yzk3ZDAwNTg4YjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjJUMDAxNDU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTc0MzIxNjhlMGE0NTgwY2ZlMjVlODRhMGMxNmI5NjhjYjQwY2NkZmQwNjVjZGVkNGM4YzgxNGE4MmEzOTBmMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CDeuOrBFiaeM6pTdysWHOlz3thS6ha_1qSXymGt3ohQ)

I can still replicate the issue, without other addons, it just takes time to replicate.
Last time I was able to replicate it, I let myself go AFK for a while, then went and did some quests and that triggered the issue with the item icon near quests.

**Comment by Noughter** [comment]
Same Problem. I even tried using Kaliels Tracker and that didnt fix it

**Comment by plinio1980** [comment]
+1

**Comment by kodewdle** [comment]
no fix atm because i can't reproduce this.  try with `/edebug on` for now.  it's very easily broken, if i can find reproduction steps i can start to look for a fix.

**Comment by bartkoevoets** [comment]
I think you can reproduce it at any time by first selecting the quest, then attempting to use the quest item from the quest log. It's very inconsistent with throwing the protected function lua error though.

**Comment by Selenagor** [comment]
Hello! Sorry for my English (I speak it very poorly, I used a translator) ^^'
 I have a similar problem, but I get a different error. I tried disabling all addons except ElvUI, the error appears immediately when I try to click on a quest item. If you disable ElvUI or simply reload the interface with ElvUI enabled, the error goes away. I can collect taint log data, since I have already managed to reproduce the error more than once.

This is the error that comes out:

1x [ADDON_ACTION_FORBIDDEN] AddOn 'ElvUI_Libraries' tried to call the protected function 'UseQuestLogSpecialItem()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `UseQuestLogSpecialItem'
[string "@Blizzard_ObjectiveTracker/Blizzard_ObjectiveTrackerShared.lua"]:94: in function <...ObjectiveTracker/Blizzard_ObjectiveTrackerShared.lua:87>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
}

**Comment by Kirschie** [comment]
+1 can't use the quest items from the UI next to the quest objective

![image](https://github.com/user-attachments/assets/9cea5472-49d8-4b11-8c5f-c3a21d58b362)

**Comment by NotOats** [comment]
Also got this bug recently, diagnosed it back to CopyPasta2. I am sure that's not the only addon (or combination) that could cause this but I figured it might help someone to know.

**Comment by kodewdle** [comment]
i did not get a fix for this into 13.77 however i fixed one cause of this in our dev build, please try: [elvui-main.zip](<https://api.tukui.org/v1/download/dev/elvui/main>)

**Comment by jpwalsh1** [comment]
Haven't tested above but reporting that current build from curse does this.

**Comment by kodewdle** [comment]
> Haven't tested above but reporting that current build from curse does this.

elvui isn't on curseforge

**Comment by atomic7431** [comment]
Hello,
i am using the latest version of elvui 13.78 and the quest item bug is still there.
I have to reload the ui to get the quest item to work, when its not working it makes a noise but doesnt do anything.
what do you need to help find the culprit?

**Comment by atomic7431** [comment]
update 
was handing out orders quest in warwithin and thrid time i used the quest icon and caught this error -

Date: 2024-10-03 13:24:43
ID: 1
Error occured in: AddOn: WorldQuestTracker
Count: 1
Message: Error: AddOn WorldQuestTracker attempted to call a forbidden function (UseQuestLogSpecialItem()) from a tainted execution path.
Debug:
   [string "=[C]"]: UseQuestLogSpecialItem()
   [string "@Interface/AddOns/Blizzard_ObjectiveTracker/Blizzard_ObjectiveTrackerShared.lua"]:94:
      ...ObjectiveTracker/Blizzard_ObjectiveTrackerShared.lua:87
Locals:
self = Button {
 NormalTexture = Texture {
 }
 HotKey = FontString {
 }
 questLogIndex = 2
 rangeTimer = 0.010000
 count = 0
 charges = 0
 template = "QuestObjectiveItemButtonTemplate"
 IsSkinned = true
 Count = FontString {
 }
 used = true
 icon = Texture {
 }
 Cooldown = Cooldown {
 }
}
button = "LeftButton"

AddOns:
  Swatter, v11.x.BETA.4 (TheWarWithBlizzardAPIs)
  AllTheThings, v4.0.16
  Auctionator, v11.0.12
  Auctioneer, v11.x.BETA.4 (TheWarWithBlizzardAPIs)
  AuctioneerStatsOverTime, v11.x.BETA.4 (TheWarWithBlizzardAPIs)
  AuctioneerUtilDealFinder, v11.x.BETA.4 (TheWarWithBlizzardAPIs)
  AuctioneerUtilValuer, v11.x.BETA.4 (TheWarWithBlizzardAPIs)
  CanIMogIt, v11.0.2v2.4
  DBMCore, v11.0.21
  DBMStatusBarTimers, v11.0.21
  DBMVPVEM, v6dbaa27
  DejaCharacterStats, vR110002r5
  Details, v#Details.13096.161
  DetailsTWW, vv1.3
  ElvUI, vv13.78
  ElvUILibraries, vv13.78
  ElvUIOptions, vv13.78
  FasterLoot, vv20240920
  HandyNotes, vv1.6.21
  HandyNotesBattleForAzerothTreasures, vv33
  HandyNotesDragonflight, v103
  HandyNotesDragonflightTreasures, vv64
  HandyNotesDragonGlyphs, v0.1.6
  HandyNotesShadowlands, v101
  HandyNotesShadowlandsTreasures, vv81
  HandyNotesTheWarWithin, v103
  HandyNotesWarWithin, vv67
  MBB, v4.0.26
  OPie, vØrred 1a
  Plater, vPlater-v589-Retail
  Plumber, v1.4.1
  Postal, vv4.1.9
  RareScanner, v11.0.2.18
  Simulationcraft, v11.0.2-02
  Stubby, v11.x.BETA.4 (TheWarWithBlizzardAPIs)
  UnlimitedMapPinDistance, v1.4.6
  WeakAuras, v5.17.1
  WeakAurasArchive, v5.17.1
  WorldQuestTracker, vv11.0.2.520-Retail
  BlizRuntimeLib v11.0.2.56819(EU) <enUS>
  (ck=504)

i hope it helps.

**Comment by kodewdle** [comment]
> update was handing out orders quest in warwithin and thrid time i used the quest icon and caught this error

you have a lot of other addons enabled, try with only ElvUI by typing `/edebug on`

**Comment by tajobe** [comment]
> Error occured in: AddOn: WorldQuestTracker

@atomic7431 might be worth a report over at https://github.com/Tercioo/World-Quest-Tracker/issues (if that's the right addon)

**Comment by atomic7431** [comment]
Disabled elv ui, the problem was resolved.
Enabled elv ui and disabled all addons and problem was still present.

**Comment by jpwalsh1** [comment]
Same for me after latest update, it still doesn't work but it's clearly other addons fighting this. Greenwall was one for me, not sure if the WorldQuest tracker was doing it either. But disabling all of your addons except just Elv and then enabling one by one will be about the only way to figure it out, then go open tickets like this there.

**Comment by andrewmunro** [comment]
Same for me, I can use a quest item once from the quest log, then nothing happens and I have to use from my bags instead...

**Comment by Naomimyam** [comment]
Yea no its not working. I tried everything. Turned off all my addons(individually), Used the files that was recommended earlier, turned on the debugger, and even almost ripped out my hair. Now, its tedious to go in my bag and i feel like its just too much of a hastle to even have elvui. Though i do prefer it than to have the regular ui.. but if there is a fix, that would be great.

**Comment by OMGITSJAD** [comment]
+1 feel like this has been going on for a while.

**Comment by kodewdle** [comment]
can confirm these reports, leveled a few characters.  mostly it worked but i also had it not work a couple times while leveling.  still not sure of a fix or proper way to reproduce the problem.  if anybody has steps to cause this, for example:

1) reload
2) open spellbook
3) cast a spell
4) do a little dance
5) try to use the item on quest log
6) doesnt work

this would be helpful (obviously getting it short as possible after a reload is ideal).

**Comment by Fragglerock2218** [comment]
You can go into Elvui>Information>Debug, and it works for a little bit. Haven't found a permanent fix yet. It gets really annoying when doing Delves and cannot drop the candle and such.

**Comment by jpwalsh1** [comment]
Agree, I also have an issue where the whole quest log will disappear at times, then reappear randomly too. But to solve the whole 'cant drop the delve item' bug which is why most of us are here. I just ended up making a macro.

/cancelaura Enchanted Candle
/cancelaura Air Totem
