### ISSUE TITLE
[TBC Bug Report] Unable to adjust anchor for Quest Tracker

### ISSUE THREAD

**Issue by Micrococonut** [tukui-org/ElvUI#295]
### What is the issue you are having?

I am unable to move the quest tracker panel from its position.
![image](https://user-images.githubusercontent.com/9060561/186074971-bc6085fb-9c20-4379-923e-b42b0be2bda1.png)
When I attempt to move the anchor in the editing mode, I start getting errors. 
![image](https://user-images.githubusercontent.com/9060561/186074906-b49a338e-429d-45b0-88fa-534c085c5922.png)

### What is the expected behavior?

I should be able to move the objective panel without errors.

### What actually happened?

I was unable to move the objective panel at all.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [TBC Changelog](https://www.tukui.org/classic-tbc-addons.php?id=2&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
What is the first error you receive? - 
In the screenshot (I can't see if it is error 3/4 or 2/9 etc)  it doesn't look like the first error

Click on First and post another screenshot showing the error.  As well as a screenshot, copy the error and paste it in here.

**Comment by Micrococonut** [comment]
![image](https://user-images.githubusercontent.com/9060561/186278310-0176fe36-e8b1-4d66-936f-8b4775774598.png)


**Error 1 of 2:**
Message: Interface\AddOns\ElvUI\Core\General\Movers.lua:288: attempt to compare number with nil
Time: Tue Aug 23 18:33:58 2022
Count: 305
Stack: Interface\AddOns\ElvUI\Core\General\Movers.lua:288: attempt to compare number with nil
[string "=[C]"]: ?
[string "@Interface\AddOns\ElvUI\Core\General\Movers.lua"]:288: in function `CalculateMoverPoints'
[string "@Interface\AddOns\ElvUI\Core\General\Movers.lua"]:51: in function <Interface\AddOns\ElvUI\Core\General\Movers.lua:49>

Locals: 

**Page 2 of 2:**
Message: Interface\AddOns\ElvUI\Core\General\Movers.lua:288: attempt to compare number with nil
Time: Tue Aug 23 18:33:56 2022
Count: 1
Stack: Interface\AddOns\ElvUI\Core\General\Movers.lua:288: attempt to compare number with nil
[string "=[C]"]: ?
[string "@Interface\AddOns\ElvUI\Core\General\Movers.lua"]:288: in function `CalculateMoverPoints'
[string "@Interface\AddOns\ElvUI\Core\General\Movers.lua"]:127: in function <Interface\AddOns\ElvUI\Core\General\Movers.lua:114>

Locals:

**Comment by Repooc** [comment]
dont see this issue in wrath prepatch, if so, open new ticket with updated info please
